#!/bin/bash
cat > env-inject.js << EOF
window.ENV = {
  GROQ_API_KEY: "${GROQ_API_KEY}",
  GROQ_API_URL: "${GROQ_API_URL}",
  GROQ_MODEL: "${GROQ_MODEL}",
  FIREBASE_API_KEY: "${FIREBASE_API_KEY}",
  FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}",
  FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}",
  FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}",
  FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}",
  FIREBASE_APP_ID: "${FIREBASE_APP_ID}",
  MIDNIGHT_NETWORK_URL: "${MIDNIGHT_NETWORK_URL}",
  MIDNIGHT_API_KEY: "${MIDNIGHT_API_KEY}"
};
EOF
